import NavBar from "@/component/NavBar";
import "./globals.css";
import getCurrentUser from "./action/getCurrentUser";

import type { Metadata } from "next";
// import { User } from "@prisma/client";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUserSession = await getCurrentUser();
  // console.log('cus', currentUserSession)

  return (
    <html lang="en">
      <body>
        <div>
          <NavBar currentUser={currentUserSession} />
        </div>
        <div className={
          `px-5
          sm:px-10
          py-2`
        }>
          {children}
        </div>
      </body>
    </html>
  );
}
